## Занятие 20.09.2024
1. Создать вектор (одномерный массив) размера 10, заполненый нулями
2. Создать вектор размер 10, заполненный единицами
3. Создать вектор размера 10, заполненный числом 2.5
4. Создать вектор заполненный нулями, но пятый элемент равен 1
5. Создать вектор со значениями от 10 до 49
6. Развернуть вектор (первый становится последним)
7. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
8. Найти индексы ненулевых элементов в [1,2,0,0,4,0]
9. Создать массив 3x3x3 со случайными значениями
10. Создать массив 10x10 со случайными значениями, найти минимум и максимум
11. Создать матрицу с 0 внутри и 1 на границах
12. Создать матрицу 8x8 и заполнить ее в шахматном порядке
13. Перемножить матрицы 5x3 и 3x2
14. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки
15. Есть генератор, сделать с его помощью массив
```python
def generate():
    for x in range(10):
            yield x
```
16. Создать двумерный список и преобразовать его в NumPy массив (с типом int32)
17. Проверить, одинаковы ли 2 NumPy массива
18. Сделать массив неизменяемым

In [1]:
import numpy as np

In [2]:
# Задание 1 Создать вектор (одномерный массив) размера 10, заполненый нулями
a = np.zeros((10))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Задание 2 Создать вектор размер 10, заполненный единицами
a = np.ones((10))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
# Задание 3 Создать вектор размера 10, заполненный числом 2.5
a = np.full((10), 2.5)
print(a)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [5]:
# Задание 4 Создать вектор заполненный нулями, но пятый элемент равен 1
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
# Задание 5 Создать вектор со значениями от 10 до 49
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# Задание 6 Развернуть вектор (первый становится последним)
a = np.arange(10)
b = a[::-1]
print(b)

[9 8 7 6 5 4 3 2 1 0]


In [8]:
# Задание 7 Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
a = np.arange(9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# Задание 8 Найти индексы ненулевых элементов в [1,2,0,0,4,0]
a = np.array([1,2,0,0,4,0])
b = np.argwhere(a != 0)
print(b)

[[0]
 [1]
 [4]]


In [10]:
# Задание 9 Создать массив 3x3x3 со случайными значениями
a = np.random.random((3, 3, 3))
print(a)

[[[0.97080531 0.19467054 0.72664733]
  [0.400673   0.08318574 0.96426051]
  [0.82525711 0.98554383 0.5121243 ]]

 [[0.71825299 0.04019445 0.59367176]
  [0.03627093 0.81554571 0.08538484]
  [0.38264989 0.20108966 0.91136417]]

 [[0.71779437 0.52219851 0.12837095]
  [0.03108442 0.39229068 0.85730042]
  [0.24911022 0.65264145 0.05095305]]]


In [11]:
# Задание 10 Создать массив 10x10 со случайными значениями, найти минимум и максимум
a = np.random.random((10, 10))
print(a)
print(f'max: {np.max(a)}, min: {np.min(a)}')

[[0.34657881 0.98550635 0.0292047  0.22607267 0.68706837 0.24306676
  0.27443219 0.56339296 0.36106634 0.61983628]
 [0.69050832 0.07121767 0.70901612 0.36810542 0.56455802 0.18528115
  0.05115293 0.11387413 0.26063596 0.36908292]
 [0.44557036 0.45870996 0.7354344  0.70819151 0.28097725 0.2604334
  0.57567822 0.15250984 0.87325514 0.47498298]
 [0.54890696 0.61046599 0.73758619 0.63694421 0.65459736 0.29148481
  0.4776023  0.28927324 0.46539251 0.47288035]
 [0.53940712 0.7878388  0.62590052 0.56385708 0.72050255 0.60345873
  0.28073966 0.71433578 0.91932341 0.7580679 ]
 [0.13187335 0.45646757 0.14430098 0.172763   0.82354556 0.01709647
  0.60994278 0.09709796 0.73049957 0.79771296]
 [0.35824033 0.63634622 0.5054699  0.39333735 0.12589378 0.88190887
  0.96003767 0.19674652 0.35495719 0.47132081]
 [0.30096576 0.28078753 0.18844317 0.29872377 0.16944432 0.51362823
  0.98997145 0.33917218 0.78993183 0.24396171]
 [0.23189949 0.96559336 0.84877299 0.0653961  0.40006703 0.62914603
  0.89506914 

In [12]:
# Задание 11 Создать матрицу с 0 внутри и 1 на границах
a = np.ones((10, 10))
a[1: -1, 1: -1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
# Задание 12 Создать матрицу 8x8 и заполнить ее в шахматном порядке
a = np.ones((8, 8))
a[1::2, ::2] = 0
a[::2, 1::2] = 0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [14]:
# Задание 13 Перемножить матрицы 5x3 и 3x2
a = np.arange(15).reshape((5, 3))
b = np.arange(6).reshape((3, 2))
c = np.dot(a, b)
# Или можно a.dot(b)
print(c)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [15]:
# Задание 14 Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки
a = np.random.random((5, 7))
print(a)
b = np.delete(a, [3, 5], axis = 1)
print(b)

[[0.70036087 0.51165425 0.13895026 0.25357113 0.52603174 0.56469263
  0.13557786]
 [0.87681217 0.91697903 0.43251152 0.96756005 0.4111005  0.44866912
  0.89755276]
 [0.82142388 0.31576019 0.81209119 0.20969171 0.71196055 0.6924681
  0.14767848]
 [0.38972089 0.84975588 0.89582729 0.59439302 0.7855458  0.82631198
  0.16545708]
 [0.57283309 0.12273278 0.45306649 0.04041584 0.88121367 0.81519512
  0.99939152]]
[[0.70036087 0.51165425 0.13895026 0.52603174 0.13557786]
 [0.87681217 0.91697903 0.43251152 0.4111005  0.89755276]
 [0.82142388 0.31576019 0.81209119 0.71196055 0.14767848]
 [0.38972089 0.84975588 0.89582729 0.7855458  0.16545708]
 [0.57283309 0.12273278 0.45306649 0.88121367 0.99939152]]


In [16]:
# Задание 15 Есть генератор, сделать с его помощью массив
def generate():
    for x in range(10):
            yield x
a = np.array(list(generate()))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# Задание 16 Создать двумерный список и преобразовать его в NumPy массив (с типом int32)
a = list([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array(a, dtype=np.int32)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Задание 17 Проверить, одинаковы ли 2 NumPy массива
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
c = np.array([4, 5, 6])
print(f'a == b : {np.array_equal(a, b)}')
print(f'a == c : {np.array_equal(a, c)}')

a == b : True
a == c : False


In [19]:
# Задание 18 Сделать массив неизменяемым
a = np.array([1, 2, 3])
a.flags.writeable = False
try:
    a[1] = 13
    print(a)
except Exception as exc:
    print(f"Возникло исключение {exc}")

a.flags.writeable = True
a[1] = 13
print(a)

Возникло исключение assignment destination is read-only
[ 1 13  3]
